server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;

    # Support large uploads and streaming to backend APIs
    client_max_body_size 6g;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;

    location / {
        index index.html;
        try_files $uri /index.html;
    }
}